# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField(max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
